### ISSUE TITLE
FashionIQ dataset

### ISSUE THREAD

**Issue by develop-productivity** [Code-kunkun/ZS-CIR#1]
The FashionIQ dataset has a lot of broken urls, can you provide a copy of the dataset you used? It can be google drive or Baidu network disk, or you can contact me by email

**Comment by Code-kunkun** [comment]
I think you can download the fashioniq dataset using the link in [this issue](https://github.com/XiaoxiaoGuo/fashion-iq/issues/18)
I hope this solves your problem.

**Comment by develop-productivity** [comment]
> I think you can download the fashioniq dataset using the link in [this issue](https://github.com/XiaoxiaoGuo/fashion-iq/issues/18) I hope this solves your problem.

Thanks!
