### ISSUE TITLE
why does your code converge so fast?

### ISSUE THREAD

**Issue by May2333** [Code-kunkun/ZS-CIR#2]
Hi,
  thanks for your work!
  I found that your code is based on CLIP4CIR, but when I use CLIP4CIR, I need to train the model for 300 epochs to converge. However, your code requires only 100 epochs. 
  My question is: Is the scheduler (you add it in your code) the key setting that causes your code to converge in a few epochs? But I also use your setting in the original CLIP4CIR, it doesn't work.
  Any reply will be helpful!

**Comment by Code-kunkun** [comment]
Hello, thank you for your interest in our work. The setting of CLIP4CIR is supervised, and our setting is zero-shot. I think this is the most critical factor why we converge quickly. Moreover, CLIP4CIR did not need 300 epochs to converge during my experiment, that is, after training some epochs, it can approach the effect shown on his paper. Regarding the scheduler, I didn't do a corresponding ablation study to verify whether it is related to the convergence speed, but I think it should not be related.
Hope this can figure out your question.

**Comment by May2333** [comment]
Thank you for your quick reply which resolved my confusion. So it may be other factors, maybe the different dataset.
Thanks again.
