### ISSUE TITLE
Visualisation Code

### ISSUE THREAD

**Issue by vkg2001** [Code-kunkun/ZS-CIR#3]
Hi.
Thank you for the work.
Can you share the code to visualise the same once training is done?
It'll be of great help!

**Comment by Code-kunkun** [comment]
I'm sorry, because this part of the code is a bit messy, I don't plan to make it public, but the core idea is to use the attention map in the transformer encoder to perform corresponding visualization operations. I hope this can help you.

**Comment by vkg2001** [comment]
Thank you for the response. Can that some part be shared wherein I just wanted to visualize what output I get when I give an image and text as input? I just want to see ouput of how it shows. It will of great help.
