### ISSUE TITLE
Thanks to the authors for their excellent work, I would like to know if it is possible to upload the code for dataset construction (i.e., template-based and LLM-based) to understand the complete process?

### ISSUE THREAD

**Issue by lz75258** [Code-kunkun/ZS-CIR#5]

**Comment by Code-kunkun** [comment]
Sorry, I have not organized this part of the code. The processing details of the template-based method can be found in the appendix, and the prompt to drive LLM has also been provided in the paper. If you are not clear about any details, please feel free to ask me questions!

**Comment by caoziyang1997** [comment]
> _No description provided._

Could you please send me your laion_coco_metadata_600m dataset? I can't find it online anymore. Thank you！

**Comment by caoziyang1997** [comment]
> Sorry, I have not organized this part of the code. The processing details of the template-based method can be found in the appendix, and the prompt to drive LLM has also been provided in the paper. If you are not clear about any details, please feel free to ask me questions!

Could you please send me your laion_coco_metadata_600m dataset? I can't find it online anymore. Thank you！

**Comment by Code-kunkun** [comment]
I am sorry for the late reply. I have uploaded the related files to the [google drive](https://drive.google.com/drive/folders/1EGpylkOMj9tduUjAhTLtaX5UqjPMyN3X?usp=sharing). If you have any questions, please don't hesitate to ask me!
