### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by caoziyang1997** [Code-kunkun/ZS-CIR#6]
Could you please send me your laion_coco_metadata_600m dataset? I can't find it online anymore. Thank you！

**Comment by Code-kunkun** [comment]
I am sorry for the late reply. I have uploaded the related files to the [google drive](https://drive.google.com/drive/folders/1EGpylkOMj9tduUjAhTLtaX5UqjPMyN3X?usp=sharing). If you have any questions, please don't hesitate to ask me!
