### ISSUE TITLE
数据集缺少标注文本

### ISSUE THREAD

**Issue by HaHaJun1101** [Code-kunkun/ZS-CIR#7]
当我下载完 laion_cir 并解压过后，我发现里面缺少了标注文本 ( modified text)，同时，也缺少了对应的三元组的图像标注 (Refernce Image and Target Image name)，当然，还有 Refernce Image and Target Image 的 Caption 请问有什么途径可以获取他们么？非常感谢！

**Comment by Code-kunkun** [comment]
I am sorry for the late reply. I have uploaded the related files to the [google drive](https://drive.google.com/drive/folders/1EGpylkOMj9tduUjAhTLtaX5UqjPMyN3X?usp=sharing), and the modified text is already included in the data/files/laion_(combined/llm/template)_info.json. If you have any questions, please don't hesitate to ask me!
